spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 395540252447-56ipmmebnq3n1ocq83nhc1j9u7lchrr2.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
server:
  port: 8080
  